os: linux
dist: bionic
arch: amd64
language: generic

jobs:
  include:
  - stage: Build
    name: "Build dependencies"
    services: docker
    before_script:
      - git clone https://github.com/binrats/gtirb
      - git clone https://github.com/binrats/gtirb-pprinter
      - docker pull binrats/ddisasm-base
      - docker run -d -t --name binrattester -w /ddisasm --mount src="$(pwd)",target=/ddisasm,type=bind binrats/ddisasm-base /bin/sh
    script:
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb && git checkout -b d3 D3.0 && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb-pprinter && git checkout -b d3 D3.0 && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm && cmake -DLIEF_ROOT=/usr . -Bbuild && cd build && make install -j2"
        # Now register the new libraries so they are usable
      - docker exec binrattester /bin/sh -c "ldconfig"
        # Currently calling help returns an error code ...
      - docker exec binrattester /bin/sh -c "ddisasm --help || true"
    after_script: docker container stop binrattester
